### ISSUE TITLE
Arrow keys do not work for scrolling list

### ISSUE THREAD

**Issue by yokelpole** [bradens/tabba#10]
Tabba does not scroll through the displayed tabs when `next` and `previous` settings are bound to `ArrowUp` and `ArrowDown`.

**Comment by yokelpole** [comment]
Adding to note that this bug only seems to happen on the extension distributed from the Chrome web store.

After some inspecting I can see that even if I have changed the keybindings in the settings and reload the extension when I set a breakpoint @ https://github.com/bradens/tabba/blob/master/src/js/popup/index.js#L27 the `options` are unchanged from the defaults. 

This is not the case when I build the extension locally - `options` include the new keybindings and they work as expected.

**Comment by bradens** [comment]
Thanks for this! It looks like the current store version didn't have some of the key handling code that master did.  I have deployed version 0.0.2 to the store, which works for arrow keys.
